# Generated by Django 5.2.1 on 2025-05-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_ticker', models.CharField(max_length=20)),
                ('content_type', models.CharField(max_length=100)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('fiscal_quarter', models.CharField(blank=True, max_length=10, null=True)),
                ('published_date', models.DateField()),
                ('is_missing', models.BooleanField(default=False)),
                ('r2_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
