# Generated by Django 5.2.1 on 2025-05-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_document_content_name_document_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
